kind: PodChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: pod-fault-kill-experiment
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      app.kubernetes.io/component: product-catalog
  mode: all
  action: pod-kill
  gracePeriod: 0
